### ISSUE TITLE
org.jboss.el.cache.BeanPropertiesCache leaks memory in static void clear(ClassLoader classLoader)

### ISSUE THREAD

**Issue by alpapad** [jboss/jboss-el-api_spec#19]
Hi,

The method clear in BeanPropertiesCache  does not really clear the properties since it does not iterate over the nested SoftConcurrentHashMap.map but on the empty SoftConcurrentHashMap.super.

Line 194 should really be:

Iterator<Map.Entry<Class<?>, BeanProperties>> it = properties.**map**.entrySet().iterator();

(instead of properties.entrySet().iterator())

**Comment by scottmarlow** [comment]
Any suggestions for how to recreate this leak?  I tried deploying/deploying the test attached to https://issues.jboss.org/browse/WFLY-3365 but the properties/properties.map are always empty.

**Comment by alpapad** [comment]
I am using jsf and the map gets filled once I hit a page with el expressions.

I have added a break-point in method clear and I examine the contents of the iterator. The underlying map reports as being empty while the nested map is filled with weld proxies and Class<?> references. 

Please see the two screenshots

What we are experiencing is a leaks in wildfly itself while redeploying and since we are developing a solution and redeploy quite often per hour, after a few re-deployments we need to restart the server. We came across this piece of code by accident, and thought it makes sense to report.

![screenshot from 2016-03-09 21-04-45](https://cloud.githubusercontent.com/assets/1186525/13646998/bbc9c854-e63a-11e5-8d1a-49ba6b9a5e0f.png)
![screenshot from 2016-03-09 21-04-55](https://cloud.githubusercontent.com/assets/1186525/13647000/bfb1fb4e-e63a-11e5-8453-2651153e89c5.png)

**Comment by scottmarlow** [comment]
Thanks, with your encouragement I now have a non-empty properties list :)  The WildFly org.jboss.as.test.integration.jsf.beanvalidation.cdi.BeanValidationCdiIntegrationTestCase test has some EL on JSF.

**Comment by scottmarlow** [comment]
I opened https://issues.jboss.org/browse/JBEE-163 for this issue (since I prefer to track these issues with JBEE-nnn jiras).  I referenced this issue from there.  I'll close this now,  please refer to JBEE-163.
